version: '3'
services:
  ubuntu-base:
    build:
      context: ./
      dockerfile: Dockerfile-base
    stdin_open: true
    tty: true
  python:
    build:
      context: ./python
      dockerfile: Dockerfile-python
    stdin_open: true
    tty: true
    volumes:
      - ${PYTHON_WORKSPACE}:/workspace
  php5:
    build:
      context: ./php5
      dockerfile: Dockerfile-php
    stdin_open: true
    tty: true
    volumes:
      - ${PHP_WORKSPACE}:/workspace